import tkinter
w=tkinter.Tk()
w.geometry('500x200')
w.title('练习')
w.update()
width=w.winfo_width()
height=w.winfo_height()
print("当前窗口的宽度为",width)
print("当前窗口的高度为",height)
init_EntryValue=tkinter.StringVar()
init_EntryValue.set('zhizhe214@163.com')
e=tkinter.Entry(w,bg='#4f5555',fg='white',text=init_EntryValue,relief='sunken',justify='right')
# e=tkinter.Entry(w,bg='black',fg='white',text=init_EntryValue).place(x=width/2,y=height/2)
# e.pack(expand='yes',fill='x')
e.pack(side='right')
e.pack(side=tkinter.RIGHT)
w.mainloop()